# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pr:
- main

pool:
  vmImage: 'macos-latest'

jobs:
- job: BuildAndUpload
  steps:
  - bash: curl -Ls https://install.tuist.io | bash
    displayName: Install Tuist
  - bash: tuist fetch
    displayName: Fetch SPM
  - bash: tuist cache warm
    displayName: Cache dependencies
  - bash: tuist generate
    displayName: Generate Workspace
  - task: ArtifactoryGenericDownload@3
    inputs:
      connection: 'arti'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
              "pattern": "default-generic-local/testcache/*",
              "target": "~/.tuist/Cache/TestsCache/"
            }
          ]
        }
      failNoOp: true
  - bash: tuist test TuistCache-Workspace
    displayName: Test
  - task: ArtifactoryGenericUpload@2
    inputs:
      artifactoryService: 'arti'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
              "pattern": "~/.tuist/Cache/TestsCache/*",
              "target": "default-generic-local/testcache/"
            }
          ]
        }
      failNoOp: false
