# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pr:
- main

pool:
  vmImage: 'macos-latest'

variables:
  test_cache: $(HOME)/.tuist/Cache/TestsCache

jobs:
- job: BuildAndUpload
  steps:
  - bash: curl -Ls https://install.tuist.io | bash
    displayName: Install Tuist
  - bash: tuist fetch
    displayName: Fetch SPM
  - task: Cache@2
    inputs:
      key: 'spm | "$(Agent.OS)" | "$(Build.SourceBranch)" | "$(Build.BuildId)"'
      restoreKeys: |
        spm | "$(Agent.OS)" | "$(Build.SourceBranch)"
        spm | "$(Agent.OS)" | refs/heads/main
      path: $(test_cache)
  - bash: tuist test TuistCache-Workspace
    displayName: Test  